name: My First Work flow

on: push

jobs:
  list_system_usages:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome message
        run: echo "My First github action Job"
      - name: list files
        run: ls
      - name: Get File content
        run: cat README.md