name: Third job
on: push
jobs:
    third-job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v5.0.0
        - name: check system detail
          run: | 
                chmod +x cowsay-script.sh
                ./cowsay-script.sh