name: Third job
on: push
jobs:
    third-job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v5.0.0
        - name: check system detail
          run: | 
                ls -lrth
                cat README.md
                echo "Today date is $(date)"
                sudo apt-get install cowsay -y
        - name: Print ASCI content
          run: cowsay -f dragon "This is DRGAON ..." >> dragon.txt
        - name: Verify dragon
          run: grep -i dragon dragon.txt
        - name: Read file
          run: cat dragon.txt