name: Exporting Variables and secrets
on: push
env:
    CONTAINER_REGISTRY: docker.io
    DOCKER_USERNAME: mukeshvr89
    IMAGE_NAME: github-actions-nginx
jobs:
    docker:    
        runs-on: ubuntu-latest
        steps:             
            - name: Dcoker build
              run: echo docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            
            - name: Docker login
              env:
                DOCKER_PASSWORD: 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
              run: echo docker login --username=${{ env.DOCKER_USERNAME}} --password=${{ env.DOCKER_PASSWORD}}
            - name: Docker publish
              run: echo docker push ${{ env.CONTAINER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
 
    deploy:
        runs-on: ubuntu-latest
        needs: docker
        steps:
          - name: Docker login
            env:
                DOCKER_PASSWORD: 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
              run: echo docker login --username=${{ env.DOCKER_USERNAME}} --password=${{ env.DOCKER_PASSWORD}}
          - name: Docker run test
            run: docker run -d -p 8080:80 ${{ env.CONTAINER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
