name: Exporting Variables and secrets
on: push
jobs:
  self-hosted:
    runs-on: [self-hosted,Linux,main]
    steps:
      - name: "Check self hosted runner"
        run: | 
             echo "Self hosted runner check"
