name: Exporting Variables and secrets
on: push
jobs:
    docker:    
        runs-on: ubuntu-latest
        steps:             
            - name: Docker build
              run: echo docker build -t ${{ vars.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:latest
            
            - name: Docker login
              run: echo docker login ${{ vars.CONTAINER_REGISTRY }}  --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
            - name: Docker publish
              run: echo docker push ${{ vars.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:latest
 
    deploy:
        runs-on: ubuntu-latest
        needs: docker
        steps:
          - name: Docker login
            run: |
                 curl -fsSL https://get.docker.com -o get-docker.sh
                 sudo sh ./get-docker.sh
                 sudo docker login ${{ vars.CONTAINER_REGISTRY }}  --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
                 sudo docker run -d -p 8080:80 ${{ vars.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:latest
